environment_variables:
  # Python Configuration
  PYTHONPATH: "/workspace/src"
  PYTHON_VERSION: "3.11"
  
  # ML Model Configuration
  MODEL_PATH: "/models/fraud-detection-v2.1.3.pkl"
  MODEL_THRESHOLD: "0.75"
  BATCH_SIZE: "100"
  
  # Queue Configuration
  RABBITMQ_URL: "amqp://fraud-queue:5672"
  QUEUE_NAME: "transaction-analysis"
  PREFETCH_COUNT: "10"
  
  # Database
  POSTGRES_URL: "postgresql://fraud-db:5432/fraud_analytics"
  REDIS_URL: "redis://model-cache:6379"
  
  # Feature Engineering
  FEATURE_STORE_ENDPOINT: "http://feature-store:8080/api/v1"
  TRANSACTION_HISTORY_DAYS: "90"
  
  # Monitoring
  PROMETHEUS_PORT: "9090"
  LOG_LEVEL: "INFO"
  SENTRY_DSN: "((fraud-sentry-dsn))"

services:
  - fraud-postgres
  - fraud-rabbitmq
  - model-cache-redis
